name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ai-daemon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build ai-daemon
        working-directory: ai-daemon
        run: cargo build --verbose
      - name: Lint (clippy)
        working-directory: ai-daemon
        run: cargo clippy -- -D warnings

  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix flake check

  os-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - name: Build nixosConfigurations.patient-zero (variante QEMU)
        run: nix build .#nixosConfigurations.patient-zero.config.system.build.toplevel -L
      - name: Taille de la closure (indicateur d'empreinte)
        run: du -sh result
